config/routes.rb
Rails.application.routes.draw do
  resources :level3s
  resources :level2s
  resources :level1s
  resources :costs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/login', to: 'home#login'

  # This is where we are redirected if OmniAuth successfully authenticates
  # the user.
  match '/auth/:provider/callback', to: 'home#callback', via: [:get, :post]
  
  match '/send_mail', to: 'home#send_mail', via: [:post]

  match '/disconnect', to: 'home#disconnect', via: [:get]

end

app/models/cost.rb
class Cost < ApplicationRecord
	belongs_to :level1, foreign_key: "level1_id"
	belongs_to :level2, foreign_key: "level2_id"
	belongs_to :level3, foreign_key: "level3_id"
	has_many :persons, :dependent => :destroy
	mount_uploader :image, ImageUploader
	validates :submitter, presence: true
	validates :level1_id, presence: true
	validates :level2_id, presence: true
	validates :level3_id, presence: true
	validates :amount, presence: true, numericality: true
	validates :expense_date, presence: true
	validate :image_size_validation

	private

		def image_size_validation
			errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
		end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]
  include CostsHelper
  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    if session[:cost]
      @cost = Cost.new(session[:cost])
      session[:cost] = nil
      @cost.valid?
    else
      @cost = Cost.new
      @cost.submitter = cookies[:submitter]
      @cost.level1_id = Level1.where('name = ?', "G&A").first.id
      @cost.level2_id = Level2.where('name = ?', "Expense").first.id
    end
    @level1s = Level1.all.order(:name)
    @level2s = Level2.all.order(:name)
    @level3s = Level3.all.order(:name)
      t = Time.now
      puts t
      @costs = Cost.where("submitter = ? and cast(created_at as date) = cast(now() as date)", cookies[:submitter]).order('expense_date desc')
      puts @costs

  end

  # GET /costs/1/edit
  def edit
    @level1s = Level1.all.order(:name)
    @level2s = Level2.all.order(:name)
    @level3s = Level3.all.order(:name)
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)
    puts @cost.errors[:name]
    respond_to do |format|
      if @cost.save

        format.html { redirect_to new_cost_url, notice: 'Expense was successfully added.' }
        format.json { render :show, status: :created, location: @cost }
      else
        session[:cost] = cost_params
        format.html { redirect_to new_cost_url }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render  :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:submitter, :expense_date, :level1_id, :level2_id, :level3_id, :amount, :comments, :image, :number_of_people, :people_names, :onsite)
    end
end

app/helpers/costs_helper.rb
module CostsHelper

	def level1_default
		5
	end
	def level2_default
		3
	end

end

app/views/costs/_form.html.erb
<div class="card grey lighten-2">
<%= form_with(model: cost, local: true, :onsubmit => "ValidateForm();", :html => {:multipart => true, :name => 'costForm'}) do |form| %>
   <div class="card-content ">

  <% if cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :submitter %>
    <%= form.text_field :submitter, id: :cost_submitter %>
  </div>

  <div class="field">
    <%= form.label :expense_date %>
    <%= form.text_field :expense_date, id: :cost_expense_date, :class => "datepicker" %>
  </div>

  <div class="field">
    <div class="row">
      <div class="col m12"><label>Coding</label></div>
  
      <div class="col m4 s12">
        <%= select_tag "cost[level1_id]", options_from_collection_for_select(@level1s, :id, :name, cost.level1.id), prompt: 'Select' %>
      </div>
      <div class="col m4 s12">
        <%= select_tag "cost[level2_id]", options_from_collection_for_select(@level2s, :id, :name, cost.level2.id), prompt: 'Select' %>
      </div>
      <div class="col m4 s12">
        <% if !cost.level3.nil? %>
          <%= select_tag "cost[level3_id]", options_from_collection_for_select(@level3s, :id, :name, cost.level3.id), prompt: 'Select', class: 'level3' %>
        <% else %>
          <%= select_tag "cost[level3_id]", options_from_collection_for_select(@level3s, :id, :name), prompt: 'Select', class: 'level3' %>
        <% end %>
          </div>
    </div>
  </div>
  <div class="field hide m_and_e">
    <div class="row">
      <div class="switch col m3 s6">
        <label>Offsite <%= form.check_box :onsite %>
        <span class="lever"></span>
          Onsite
        </label>
      </div>
      <div class="col m3 s6 field">
        <%= form.label :number_of_people, 'Number of People' %>
        <%= form.number_field :number_of_people, id: :cost_number_of_people %>        
      </div>
      <div class="col m6 s12 field">
        <%= form.label :people_names, 'Names/Companies' %>
        <%= form.text_field :people_names, id: :cost_people_names %>        
      </div>      
    </div>
  </div>
 

  <div class="field">
    <div class="row">
      <div class="col m6 s12">
        <%= form.label :amount %>
        <%= form.text_field :amount, id: :cost_amount %>
      </div>
      <div class="col m6 s12">
        <div class="file-field input-field">
          <div class="btn">
            <span>Receipt</span>
              <input type="file" name="cost[image]" > 
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text" >
          </div>
        </div>
        <%= image_tag cost.image_url(:thumb) if cost.image? %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_field :comments, id: :cost_comments %>
  </div>

  </div>
  <div class="card-action">
    <%= form.submit 'Submit', class: "waves-effect waves-light btn-large" %>
  </div>
<% end %>
</div>

app/views/costs/_list.html.erb
<div id="costList">
<input class="search" placeholder="Search Expenses...">
<table class="striped responsive-table">
  <thead>
    <tr>
      <% if flag == 1 %>
        <th><%= button_tag  class: "sort", data: {sort: "submitter"} do %>Submitter<%= fa_icon("sort") %><% end %></th> 
      <% end %>
      <th>Expense date</th>
      <th class="hide-on-small-and-down"><%= button_tag  class: "sort", data: {sort: "level1"} do %>Level 1<%= fa_icon("sort") %><% end %></th>
      <th class="hide-on-small-and-down"><%= button_tag  class: "sort", data: {sort: "level2"} do %>Level 2<%= fa_icon("sort") %><% end %></th>
      <th class="hide-on-small-and-down"><%= button_tag  class: "sort", data: {sort: "level3"} do %>Level 3<%= fa_icon("sort") %><% end %></th>
      <th><%= button_tag  class: "sort", data: {sort: "amount"} do %>Amount<%= fa_icon("sort") %><% end %></th>
      <th class="hide-on-small-and-down">Receipt</th>
      <th>Comments</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody class="list">
    <% @costs.each do |cost| %>
      <tr>
        <% if flag == 1 %>
          <td class="submitter"><%=  cost.submitter %></td> 
        <% end %>
        <td class="expense-date"><%= cost.expense_date %></td>
        <td class="hide-on-small-and-down level1"><%= cost.level1.name %></td>
        <td class="hide-on-small-and-down level2"><%= cost.level2.name %></td>
        <td class="hide-on-small-and-down level3"><%= cost.level3.name %></td>
        <td class="amount"><%= number_to_currency(cost.amount, precision: 2) %></td>
        <td class="hide-on-small-and-down image"><%= image_tag cost.image_url(:thumb) if cost.image? %></td>
        <td class="comments"><%= cost.comments %></td>
        <td>
          <%= link_to fa_icon("pencil-square-o"), edit_cost_path(cost)  %>
        </td>
        <td>
          <%= link_to fa_icon("trash"), cost, method: :delete, data: { confirm: 'Are you sure?' }  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<ul class="pagination"></ul>
</div>

app/views/costs/_person_fields.html.erb
<div class="row">
  <div class="field col s5">
    <%= form.label :name %>
    <%= form.text_field :name, id: :person_name %>
  </div>
  <div class="field col s5">
    <%= form.label :company %>
    <%= form.text_field :company, id: :person_company %>
  </div>
  <div class="col s2">
    <%= form.check_box :_destroy %>
  </div>

</div>

app/views/costs/edit.html.erb
<div class="container">
<h1>Editing Cost</h1>

<%= render 'form', cost: @cost %>

<br>
<%= link_to fa_icon("backward")+'  Back', :back, class: "waves-effects waves-light btn vDarkBlue-bg" %>
</div>

app/views/costs/index.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>
	<div class="flex"><h1>Expenses</h1>
	<%= link_to 'Add Expense', new_cost_path,  :class => "waves-effect waves-light btn" %>
	</div>
	<%= render 'list', flag: 1 %>
</div>

app/views/costs/new.html.erb
<div class="container">
	<div class="row">
		<h3>New Expense</h3>
		<%= render 'form', cost: @cost %>
	</div>
	<hr>
	<div class="row">
	<% if !@costs.nil? %>
		<h5>Entered Expenses</h5>
		<%= render 'list', flag: 0 %>
	<% end %>
	</div>
</div>

app/views/costs/report.html.erb
<div class="container">
	<div class="row">
		<%= render 'form', cost: @cost %>
	</div>
	<div class="row">
	</div>
</div>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Submitter:</strong>
  <%= @cost.submitter %>
</p>

<p>
  <strong>Expense date:</strong>
  <%= @cost.expense_date %>
</p>

<p>
  <strong>Level1:</strong>
  <%= @cost.level1_id %>
</p>

<p>
  <strong>Level2:</strong>
  <%= @cost.level2_id %>
</p>

<p>
  <strong>Level3:</strong>
  <%= @cost.level3_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @cost.amount %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @cost.comments %>
</p>

<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>