config/routes.rb
Rails.application.routes.draw do
  resources :level3s
  resources :level2s
  resources :level1s
  resources :costs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/login', to: 'home#login'

  # This is where we are redirected if OmniAuth successfully authenticates
  # the user.
  match '/auth/:provider/callback', to: 'home#callback', via: [:get, :post]
  
  match '/send_mail', to: 'home#send_mail', via: [:post]

  match '/disconnect', to: 'home#disconnect', via: [:get]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expense App</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale-1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
  <header></header>
  <main>
    <%= yield %>
  </main>
  <footer>
   <div class="fixed-action-btn show-on-medium-and-up">
    <a class="btn-floating btn-large vDarkBlue">
      <i class="large material-icons">menu</i>
    </a>
    <ul>
      <li>
        <%= link_to fa_icon("search"), costs_path, :class => "btn-floating cyan lighten-1 tooltipped", :'data-position' => "left", :'data-delay' => "50",  :'data-tooltip' => "View All Expenses" %>
      </li>
      <li><a class="btn-floating grey lighten-1 tooltipped" data-position="left" data-delay="50" data-tooltip="Coming Soon">
      	<%= fa_icon "pie-chart" %></a>
      </li>
      <li><%= link_to fa_icon("sign-out"), disconnect_path, :class => "btn-floating cyan lighten-1 tooltipped", :'data-position' => "left", :'data-delay' => "50",  :'data-tooltip' => "Log Out" %>
      </li>
    </ul>
  </div>
  </footer>
  </body>
</html>